name: 'Terraform'

on:
  push:
    branches: [ "main" ]

env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      # run: |
      #   terraform init \
      #     -backend-config="storage_account_name=terraformfilesstorage" \
      #     -backend-config="container_name=statefiles" \
      #     -backend-config="key=terraform.tfstate" \
      #     -backend-config="access_key=${{ secrets.ACCESS_KEY }}" \
      #     -reconfigure

    - name: Terraform Plan
      run: terraform plan -input=false
